# Generated by Django 4.2.4 on 2023-08-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='chat_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='id телеграмм'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='телеграмм'),
        ),
    ]
