# Generated by Django 4.2.4 on 2023-08-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20, verbose_name='место')),
                ('time_start', models.TimeField(default='00:00:00', verbose_name='время старта')),
                ('action', models.CharField(max_length=50, verbose_name='действие')),
                ('is_pleasure', models.BooleanField(default=False, verbose_name='приятная привычка')),
                ('periodic', models.IntegerField(verbose_name='периодичность')),
                ('reward', models.CharField(max_length=50, verbose_name='вознаграждение')),
                ('execution_time', models.TimeField(default='00:01:00', verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='публикация')),
                ('is_connect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
